[package]
name = "be-config"
version = "0.1.0"
edition = "2024"

[dependencies]
be-config-macros = { path = "../be-config-macros" }

serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"

[dev-dependencies]
expect-test.workspace = true
