[font]
size = 16
family = "monospace"

[editor]
scroll-offset = 0
indent-width = 2

[[layout.tab]]
pane = "terminal"

[[layout.tab]]
pane = "split"
axis = "vertical"
percent = [0.2]
active = 1
children = [
  { pane = "file-tree" },
  { pane = "editor" },
]

[[layout.tab]]
pane = "terminal"

[language.rust]
tree-sitter = "https://github.com/tree-sitter/tree-sitter-rust"
lsp.command = "rust-analyzer"

[language.toml]
tree-sitter = "https://github.com/tree-sitter-grammars/tree-sitter-toml"

[language.markdown]
tree-sitter = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
