[font]
size = 16
family = "monospace"

[editor]
scroll-offset = 0

[language.rust]
tree-sitter = "https://github.com/tree-sitter/tree-sitter-rust"
lsp.command = "rust-analyzer"

# TODO
# toml => "https://github.com/tree-sitter-grammars/tree-sitter-toml"
# markdown => "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
