[package]
name = "be-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
be-task = { path = "../be-task" }
crossbeam-channel = "0.5.15"

lsp-types = "0.97.0"
polling = "3.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["raw_value"] }
